### ISSUE TITLE
Current release fails to build with apertium-3.5.2

### ISSUE THREAD

**Issue by bentley** [apertium/apertium-nno#1]
The latest release of apertium-nno, 0.9.0, doesn’t include the bugfix in 404dcb612d15c5c6ab2f3dfde7160ea9024ec8f8. As a result, it fails to build with apertium-3.5.2:

    stand-alone o or O doesn't make sense - maybe you meant 0?

Is nno in shape for a new release?

**Comment by unhammer** [comment]
I'm doing quite a lot with nno these days, but am planning on making a new release. I have to include the rest of the Scandinavian pairs too though, to avoid bad inconsistencies.

Btw, isn't it vislcg3 giving the error message?

**Comment by TinoDidriksen** [comment]
That is indeed a CG-3 error. Same goes for https://github.com/apertium/apertium-hbs/issues/2 , https://github.com/apertium/apertium-hbs-slv/issues/1 , https://github.com/apertium/apertium-isl-swe/issues/4
